# Generated by Django 5.1.15 on 2026-07-08 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("students", "0003_alter_student_rg_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("academic_year", models.PositiveIntegerField(verbose_name="Ano Letivo")),
                (
                    "application_number",
                    models.CharField(max_length=30, unique=True, verbose_name="Protocolo"),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("NEW", "Nova Matricula"),
                            ("REENROLL", "Rematricula"),
                            ("TRANSFER_INTERNAL", "Transferencia Interna"),
                            ("TRANSFER_EXTERNAL", "Transferencia Externa"),
                        ],
                        default="NEW",
                        max_length=30,
                        verbose_name="Tipo de Solicitacao",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRE_ENROLLMENT", "Pre-Matricula"),
                            ("UNDER_REVIEW", "Em Analise"),
                            ("APPROVED", "Aprovado"),
                            ("ENROLLED", "Matriculado"),
                            ("REJECTED", "Recusado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PRE_ENROLLMENT",
                        max_length=30,
                        verbose_name="Situacao",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Prioridade"),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observacoes")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Data de Revisao"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, default="", verbose_name="Motivo de Recusa"),
                ),
                (
                    "correction_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Solicitacao de Correcao"
                    ),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Escola de Origem"
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_applications",
                        to="classes.class",
                        verbose_name="Turma",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="classes.enrollment",
                        verbose_name="Matricula Efetivada",
                    ),
                ),
                (
                    "previous_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_from_applications",
                        to="classes.class",
                        verbose_name="Turma de Origem",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_applications",
                        to="students.student",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitacao de Matricula",
                "verbose_name_plural": "Solicitacoes de Matricula",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("BIRTH_CERT", "Certidao de Nascimento"),
                            ("ID", "Documento de Identidade"),
                            ("CPF", "CPF"),
                            ("ADDRESS", "Comprovante de Endereco"),
                            ("TRANSCRIPT", "Historico Escolar"),
                            ("MEDICAL", "Atestado Medico"),
                            ("PHOTO", "Foto 3x4"),
                            ("VACCINE", "Carteira de Vacinacao"),
                            ("CUSTODY", "Termo de Guarda"),
                            ("TRANSFER_LETTER", "Carta de Transferencia"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Descricao"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("SUBMITTED", "Entregue"),
                            ("VERIFIED", "Verificado"),
                            ("REJECTED", "Recusado"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="Situacao",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/students/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Data de Verificacao"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="enrollments.enrollmentapplication",
                        verbose_name="Solicitacao",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="students.student",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Aluno",
                "verbose_name_plural": "Documentos dos Alunos",
                "ordering": ["document_type"],
            },
        ),
        migrations.AddIndex(
            model_name="enrollmentapplication",
            index=models.Index(fields=["status"], name="enrollments_status_fdb243_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollmentapplication",
            index=models.Index(
                fields=["application_number"], name="enrollments_applica_62070b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentapplication",
            index=models.Index(
                fields=["student", "academic_year"], name="enrollments_student_e878a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(fields=["student", "status"], name="enrollments_student_3fc920_idx"),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["application", "document_type"], name="enrollments_applica_81f646_idx"
            ),
        ),
    ]
