# Generated by Django 5.1.15 on 2026-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentapplication",
            name="cancellation_reason",
            field=models.TextField(blank=True, default="", verbose_name="Motivo de Cancelamento"),
        ),
    ]
