# Generated by Django 5.2.16 on 2026-07-13 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('recipient', models.CharField(blank=True, default='', max_length=255, verbose_name='Destinatario')),
                ('street', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, default='', max_length=255, verbose_name='Complemento')),
                ('district', models.CharField(max_length=150, verbose_name='Bairro')),
                ('postal_code', models.CharField(max_length=9, verbose_name='CEP')),
                ('city', models.CharField(max_length=150, verbose_name='Municipio')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessUnitAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=True, verbose_name='Principal')),
            ],
            options={
                'verbose_name': 'Endereco da Empresa',
                'verbose_name_plural': 'Enderecos da Empresa',
            },
        ),
        migrations.CreateModel(
            name='GuardianAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=True, verbose_name='Principal')),
            ],
            options={
                'verbose_name': 'Endereco do Responsavel',
                'verbose_name_plural': 'Enderecos do Responsavel',
            },
        ),
        migrations.CreateModel(
            name='SchoolAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=True, verbose_name='Principal')),
            ],
            options={
                'verbose_name': 'Endereco da Escola',
                'verbose_name_plural': 'Enderecos da Escola',
            },
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=True, verbose_name='Principal')),
            ],
            options={
                'verbose_name': 'Endereco do Aluno',
                'verbose_name_plural': 'Enderecos do Aluno',
            },
        ),
        migrations.CreateModel(
            name='TeacherAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=True, verbose_name='Principal')),
            ],
            options={
                'verbose_name': 'Endereco do Professor',
                'verbose_name_plural': 'Enderecos do Professor',
            },
        ),
    ]
