# Generated by Django 5.1.15 on 2026-07-02 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0002_school_contact_email_school_contact_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladdress',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.school', verbose_name='Escola'),
        ),
    ]
