# Generated by Django 5.1.15 on 2026-07-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0005_seed_states_and_cities"),
        ("locations", "0002_seed_states_and_cities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='state',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='state',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
