# Generated by Django 5.1.15 on 2026-07-06 23:59

from django.db import migrations


def clear_invalid_legacy_locations(apps, schema_editor):
    """Remove valores legados de cidade/UF que nao existem mais no catalogo."""
    Address = apps.get_model("addresses", "Address")
    State = apps.get_model("locations", "State")
    City = apps.get_model("locations", "City")
    address_manager = Address._base_manager

    valid_states = set(State.objects.values_list("code", flat=True))
    for address in address_manager.all().only("id", "state", "city"):
        state = (address.state or "").strip().upper()
        city = (address.city or "").strip()

        updates = {}
        if state not in valid_states:
            updates["state"] = ""
            updates["city"] = ""
        elif city and not City.objects.filter(state__code=state, name=city).exists():
            updates["city"] = ""

        if updates:
            address_manager.filter(pk=address.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0006_remove_state_created_by_remove_state_deleted_by_and_more"),
        ("locations", "0002_seed_states_and_cities"),
    ]

    operations = [
        migrations.RunPython(
            clear_invalid_legacy_locations,
            migrations.RunPython.noop,
        ),
    ]
