# Generated by Django 5.2.16 on 2026-07-11 01:08

import base.upload_validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('enrollment_number', models.CharField(max_length=30, unique=True, verbose_name='Matrícula')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não Binário'), ('NI', 'Prefiro não informar')], default='NI', max_length=2, verbose_name='Gênero')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3, verbose_name='Tipo Sanguíneo')),
                ('special_needs', models.TextField(blank=True, default='', max_length=250, verbose_name='Necessidades Especiais')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', validators=[base.upload_validators.validate_image_upload], verbose_name='Foto')),
                ('nationality', models.CharField(blank=True, default='Brasileiro(a)', max_length=100, verbose_name='Nacionalidade')),
                ('cpf', models.CharField(blank=True, default=None, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('rg_number', models.CharField(blank=True, default='', max_length=20, verbose_name='RG — Número')),
                ('rg_issuer', models.CharField(blank=True, default='', max_length=50, verbose_name='RG — Órgão Emissor')),
                ('rg_state', models.CharField(blank=True, default='', max_length=2, verbose_name='RG — UF')),
                ('phone_mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail do Aluno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['cpf'], name='students_st_cpf_eeb4b2_idx'), models.Index(fields=['enrollment_number'], name='students_st_enrollm_667751_idx')],
            },
        ),
    ]
