# Generated by Django 5.2.16 on 2026-07-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='special_needs',
            new_name='observations',
        ),
        migrations.AddField(
            model_name='student',
            name='accepts_email_notifications',
            field=models.BooleanField(default=False, verbose_name='Aceita notificações por e-mail'),
        ),
        migrations.AddField(
            model_name='student',
            name='accepts_whatsapp_notifications',
            field=models.BooleanField(default=False, verbose_name='Aceita notificações por WhatsApp'),
        ),
        migrations.AlterField(
            model_name='student',
            name='observations',
            field=models.TextField(blank=True, default='', max_length=250, verbose_name='Observações'),
        ),
    ]
