# Generated by Django 5.1.15 on 2026-07-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_cpf_student_email_student_nationality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="rg_state",
            field=models.CharField(blank=True, default="", max_length=2, verbose_name="RG — UF"),
        ),
    ]
