# Generated by Django 5.2.16 on 2026-07-11 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Capacidade')),
                ('type', models.CharField(choices=[('CLASSROOM', 'Sala de Aula'), ('LAB', 'Laboratório'), ('GYM', 'Quadra'), ('LIBRARY', 'Biblioteca'), ('AUDITORIUM', 'Auditório'), ('OTHER', 'Outro')], default='CLASSROOM', max_length=20, verbose_name='Tipo')),
                ('resources', models.JSONField(blank=True, default=dict, verbose_name='Recursos')),
                ('floor', models.CharField(blank=True, default='', max_length=20, verbose_name='Andar')),
                ('building', models.CharField(blank=True, default='', max_length=50, verbose_name='Prédio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['building', 'floor', 'name'],
            },
        ),
    ]
