# Generated by Django 5.2.16 on 2026-07-11 21:50

from django.db import migrations, models


def copy_resources_to_observations(apps, schema_editor):
    """Preserva recursos existentes em representação textual legível."""
    Room = apps.get_model("rooms", "Room")
    for room in Room.objects.exclude(resources={}):
        room.observations = "\n".join(
            f"{key}: {value}" for key, value in sorted((room.resources or {}).items())
        )
        room.save(update_fields=["observations"])


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.RunPython(copy_resources_to_observations, migrations.RunPython.noop),
    ]
