# Generated by Django 5.2.16 on 2026-07-13 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('grade', models.CharField(choices=[('EARLY_NURSERY_1', 'Berçário I'), ('EARLY_NURSERY_2', 'Berçário II'), ('EARLY_MATERNAL_1', 'Maternal I'), ('EARLY_MATERNAL_2', 'Maternal II'), ('EARLY_PRE_1', 'Pré I'), ('EARLY_PRE_2', 'Pré II'), ('ELEMENTARY_1', '1º Ano'), ('ELEMENTARY_2', '2º Ano'), ('ELEMENTARY_3', '3º Ano'), ('ELEMENTARY_4', '4º Ano'), ('ELEMENTARY_5', '5º Ano'), ('ELEMENTARY_6', '6º Ano'), ('ELEMENTARY_7', '7º Ano'), ('ELEMENTARY_8', '8º Ano'), ('ELEMENTARY_9', '9º Ano'), ('HIGH_SCHOOL_1', '1ª Série'), ('HIGH_SCHOOL_2', '2ª Série'), ('HIGH_SCHOOL_3', '3ª Série'), ('OTHER', 'Outra')], max_length=30, verbose_name='Série')),
                ('education_stage', models.CharField(choices=[('EARLY_CHILDHOOD', 'Educação Infantil'), ('ELEMENTARY_I', 'Ensino Fundamental — Anos Iniciais'), ('ELEMENTARY_II', 'Ensino Fundamental — Anos Finais'), ('HIGH_SCHOOL', 'Ensino Médio'), ('OTHER', 'Outra')], default='OTHER', max_length=20, verbose_name='Etapa de Ensino')),
                ('shift', models.CharField(choices=[('MORNING', 'Matutino'), ('AFTERNOON', 'Vespertino'), ('NIGHT', 'Noturno'), ('FULL', 'Integral')], default='MORNING', max_length=10, verbose_name='Turno')),
                ('academic_year', models.PositiveIntegerField(verbose_name='Ano Letivo')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Vagas')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('enrollment_date', models.DateField(verbose_name='Data de Matrícula')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('TRANSFERRED', 'Transferida'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Situação')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo de Cancelamento')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
