# Generated by Django 5.2.16 on 2026-07-11 01:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('grade', models.CharField(max_length=30, verbose_name='Série')),
                ('shift', models.CharField(choices=[('MORNING', 'Matutino'), ('AFTERNOON', 'Vespertino'), ('NIGHT', 'Noturno'), ('FULL', 'Integral')], default='MORNING', max_length=10, verbose_name='Turno')),
                ('academic_year', models.PositiveIntegerField(verbose_name='Ano Letivo')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Vagas')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('enrollment_date', models.DateField(verbose_name='Data de Matrícula')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('TRANSFERRED', 'Transferida'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Situação')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo de Cancelamento')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
