# Generated by Django 5.2.16 on 2026-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='education_stage',
            field=models.CharField(choices=[('EARLY_CHILDHOOD', 'Educação Infantil'), ('ELEMENTARY_I', 'Ensino Fundamental — Anos Iniciais'), ('ELEMENTARY_II', 'Ensino Fundamental — Anos Finais'), ('HIGH_SCHOOL', 'Ensino Médio'), ('OTHER', 'Outra')], default='OTHER', max_length=20, verbose_name='Etapa de Ensino'),
        ),
    ]
