# Generated by Django 5.2.16 on 2026-07-12

from django.db import migrations, models


GRADE_ALIASES = {
    "berçário i": "EARLY_NURSERY_1",
    "bercario i": "EARLY_NURSERY_1",
    "berçário ii": "EARLY_NURSERY_2",
    "bercario ii": "EARLY_NURSERY_2",
    "maternal i": "EARLY_MATERNAL_1",
    "maternal ii": "EARLY_MATERNAL_2",
    "pré i": "EARLY_PRE_1",
    "pre i": "EARLY_PRE_1",
    "pré ii": "EARLY_PRE_2",
    "pre ii": "EARLY_PRE_2",
    "outra": "OTHER",
}
for number in range(1, 10):
    for ordinal in (f"{number}º", f"{number}°", f"{number}o", str(number)):
        GRADE_ALIASES[f"{ordinal} ano"] = f"ELEMENTARY_{number}"
for number in range(1, 4):
    for ordinal in (f"{number}ª", f"{number}º", f"{number}°", f"{number}a", str(number)):
        GRADE_ALIASES[f"{ordinal} série"] = f"HIGH_SCHOOL_{number}"
        GRADE_ALIASES[f"{ordinal} serie"] = f"HIGH_SCHOOL_{number}"

GRADE_LABELS = {
    "EARLY_NURSERY_1": "Berçário I",
    "EARLY_NURSERY_2": "Berçário II",
    "EARLY_MATERNAL_1": "Maternal I",
    "EARLY_MATERNAL_2": "Maternal II",
    "EARLY_PRE_1": "Pré I",
    "EARLY_PRE_2": "Pré II",
    **{f"ELEMENTARY_{number}": f"{number}º Ano" for number in range(1, 10)},
    **{f"HIGH_SCHOOL_{number}": f"{number}ª Série" for number in range(1, 4)},
    "OTHER": "Outra",
}


def normalize_grade_value(value):
    """Retorna o código conhecido ou preserva integralmente o valor legado."""
    normalized = " ".join(str(value or "").strip().casefold().split())
    return GRADE_ALIASES.get(normalized, value)


def normalize_known_grades(apps, schema_editor):
    """Normaliza apenas grafias de série reconhecidas."""
    Class = apps.get_model("classes", "Class")
    for class_obj in Class._base_manager.all().only("pk", "grade").iterator():
        normalized = normalize_grade_value(class_obj.grade)
        if normalized != class_obj.grade:
            Class._base_manager.filter(pk=class_obj.pk).update(grade=normalized)


def restore_grade_labels(apps, schema_editor):
    """Restaura os rótulos canônicos ao reverter a migration."""
    Class = apps.get_model("classes", "Class")
    for code, label in GRADE_LABELS.items():
        Class._base_manager.filter(grade=code).update(grade=label)


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_class_education_stage"),
    ]

    operations = [
        migrations.RunPython(normalize_known_grades, restore_grade_labels),
        migrations.AlterField(
            model_name="class",
            name="grade",
            field=models.CharField(
                choices=[
                    ("EARLY_NURSERY_1", "Berçário I"),
                    ("EARLY_NURSERY_2", "Berçário II"),
                    ("EARLY_MATERNAL_1", "Maternal I"),
                    ("EARLY_MATERNAL_2", "Maternal II"),
                    ("EARLY_PRE_1", "Pré I"),
                    ("EARLY_PRE_2", "Pré II"),
                    ("ELEMENTARY_1", "1º Ano"),
                    ("ELEMENTARY_2", "2º Ano"),
                    ("ELEMENTARY_3", "3º Ano"),
                    ("ELEMENTARY_4", "4º Ano"),
                    ("ELEMENTARY_5", "5º Ano"),
                    ("ELEMENTARY_6", "6º Ano"),
                    ("ELEMENTARY_7", "7º Ano"),
                    ("ELEMENTARY_8", "8º Ano"),
                    ("ELEMENTARY_9", "9º Ano"),
                    ("HIGH_SCHOOL_1", "1ª Série"),
                    ("HIGH_SCHOOL_2", "2ª Série"),
                    ("HIGH_SCHOOL_3", "3ª Série"),
                    ("OTHER", "Outra"),
                ],
                max_length=30,
                verbose_name="Série",
            ),
        ),
    ]
