# Generated by Django 5.2.16 on 2026-07-11 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('scope', models.CharField(max_length=20, verbose_name='Tipo')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='Valor Atual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sequência de Matrícula',
                'verbose_name_plural': 'Sequências de Matrícula',
                'indexes': [models.Index(fields=['scope', 'year'], name='core_regist_scope_d855d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'year'), name='uniq_reg_sequence_scope_year')],
            },
        ),
    ]
