# Generated by Django 5.1.15 on 2026-07-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail do Responsavel'),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do Responsavel'),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone do Responsavel'),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_role',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Cargo do Responsavel'),
        ),
        migrations.AddField(
            model_name='school',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razao Social'),
        ),
        migrations.AddField(
            model_name='school',
            name='municipal_registration',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscricao Municipal'),
        ),
        migrations.AddField(
            model_name='school',
            name='state_registration',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscricao Estadual'),
        ),
        migrations.AddField(
            model_name='school',
            name='trade_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome Fantasia'),
        ),
    ]
