# Generated by Django 5.1.15 on 2026-07-02 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_school_contact_email_school_contact_full_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=200, verbose_name="Nome da Empresa")),
                ("cnpj", models.CharField(blank=True, max_length=18, null=True, unique=True)),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Razao Social"
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Nome Fantasia"
                    ),
                ),
                (
                    "state_registration",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Inscricao Estadual"
                    ),
                ),
                (
                    "municipal_registration",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Inscricao Municipal"
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "contact_full_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Nome do Responsavel"
                    ),
                ),
                (
                    "contact_role",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Cargo do Responsavel"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Telefone do Responsavel",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="E-mail do Responsavel"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="business_units/logos/"),
                ),
                ("academic_year_start", models.DateField(blank=True, null=True)),
                ("academic_year_end", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="core_busine_name_2ecd21_idx"),
                    models.Index(fields=["cnpj"], name="core_busine_cnpj_79a967_idx"),
                ],
            },
        ),
    ]
