# Generated by Django 5.1.15 on 2026-06-28 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(blank=True, default="", verbose_name="Descrição")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HOMEWORK", "Tarefa"),
                            ("EXAM", "Prova"),
                            ("PROJECT", "Trabalho"),
                            ("PARTICIPATION", "Participação"),
                        ],
                        default="HOMEWORK",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de Entrega")),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, default=10.0, max_digits=5, verbose_name="Nota Máxima"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, default=1.0, max_digits=4, verbose_name="Peso na Média"
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
                "ordering": ["-due_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="ActivitySubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Nota"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Entregue em"),
                ),
                ("feedback", models.TextField(blank=True, default="", verbose_name="Feedback")),
            ],
            options={
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
