# Generated by Django 5.2.16 on 2026-07-12 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_initial'),
        ('students', '0002_remove_student_special_needs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='modality',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Em grupo')], default='INDIVIDUAL', max_length=20, verbose_name='Modalidade'),
        ),
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota do Grupo')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='Feedback do Grupo')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='activities.activity', verbose_name='Atividade')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo da Atividade',
                'verbose_name_plural': 'Grupos da Atividade',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='activities.activity', verbose_name='Atividade')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='activities.activitygroup', verbose_name='Grupo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_group_memberships', to='students.student', verbose_name='Aluno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integrante do Grupo',
                'verbose_name_plural': 'Integrantes do Grupo',
                'ordering': ['student__first_name', 'student__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='activitygroup',
            index=models.Index(fields=['activity', 'name'], name='activities__activit_bc8a7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitygroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('activity', 'name'), name='unique_active_activity_group_name'),
        ),
        migrations.AddIndex(
            model_name='activitygroupmember',
            index=models.Index(fields=['activity', 'student'], name='activities__activit_1961e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitygroupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('activity', 'student'), name='unique_active_student_activity_group'),
        ),
        migrations.AddConstraint(
            model_name='activitygroupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('group', 'student'), name='unique_active_group_student'),
        ),
    ]
