# Generated by Django 5.2.16 on 2026-07-13 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField(verbose_name='Válido a partir de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido até')),
            ],
            options={
                'verbose_name': 'Grade Horária',
                'verbose_name_plural': 'Grade Horária',
                'ordering': ['-valid_from', 'class_obj', 'time_slot__day_of_week', 'time_slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('day_of_week', models.CharField(choices=[('MON', 'Segunda'), ('TUE', 'Terça'), ('WED', 'Quarta'), ('THU', 'Quinta'), ('FRI', 'Sexta'), ('SAT', 'Sábado'), ('SUN', 'Domingo')], max_length=3, verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(verbose_name='Fim')),
                ('slot_number', models.PositiveSmallIntegerField(default=1, verbose_name='Número do Horário')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'ordering': ['day_of_week', 'slot_number'],
            },
        ),
    ]
