# Generated by Django 5.1.15 on 2026-06-29 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=50, verbose_name="Nome")),
                ("start_date", models.DateField(verbose_name="Início")),
                ("end_date", models.DateField(verbose_name="Término")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planejado"),
                            ("IN_PROGRESS", "Em Andamento"),
                            ("CLOSED", "Encerrado"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ano Letivo",
                "verbose_name_plural": "Anos Letivos",
                "ordering": ["-start_date"],
                "unique_together": {("name", "start_date")},
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(blank=True, default="", verbose_name="Descrição")),
                ("start_date", models.DateField(verbose_name="Início")),
                ("end_date", models.DateField(verbose_name="Término")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Hora de início"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Hora de término"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HOLIDAY", "Feriado/Dia não letivo"),
                            ("MEETING", "Reunião"),
                            ("SCHOOL_EVENT", "Evento Escolar"),
                            ("NON_SCHOOL_DAY", "Dia não letivo"),
                            ("ASSESSMENT", "Avaliação"),
                            ("OTHER", "Outro"),
                        ],
                        default="SCHOOL_EVENT",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "recurrence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Regra de recorrência (ex.: {'freq':'WEEKLY','interval':1}).",
                        verbose_name="Recorrência",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "Todos"),
                            ("TEACHERS", "Professores"),
                            ("STUDENTS", "Alunos"),
                            ("GUARDIANS", "Responsáveis"),
                            ("CLASS", "Turma específica"),
                        ],
                        default="ALL",
                        max_length=20,
                        verbose_name="Público-alvo",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Público para responsáveis/alunos"
                    ),
                ),
                ("is_cancelled", models.BooleanField(default=False, verbose_name="Cancelado")),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Motivo de cancelamento",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="academic_calendar.academicyear",
                        verbose_name="Ano Letivo",
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="classes.class",
                        verbose_name="Turma",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["start_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "Nacional"),
                            ("STATE", "Estadual"),
                            ("MUNICIPAL", "Municipal"),
                            ("SCHOOL", "Escolar"),
                        ],
                        default="NATIONAL",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Quando ativo, o feriado é considerado em qualquer ano.",
                        verbose_name="Repete todo ano",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feriado",
                "verbose_name_plural": "Feriados",
                "ordering": ["date"],
                "unique_together": {("name", "date")},
            },
        ),
    ]
