# Generated by Django 5.2.16 on 2026-07-13 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Término')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('IN_PROGRESS', 'Em Andamento'), ('CLOSED', 'Encerrado')], default='PLANNED', max_length=20, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Término')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de término')),
                ('type', models.CharField(choices=[('HOLIDAY', 'Feriado/Dia não letivo'), ('MEETING', 'Reunião'), ('SCHOOL_EVENT', 'Evento Escolar'), ('NON_SCHOOL_DAY', 'Dia não letivo'), ('ASSESSMENT', 'Avaliação'), ('OTHER', 'Outro')], default='SCHOOL_EVENT', max_length=20, verbose_name='Tipo')),
                ('recurrence', models.JSONField(blank=True, default=dict, help_text="Regra de recorrência (ex.: {'freq':'WEEKLY','interval':1}).", verbose_name='Recorrência')),
                ('audience', models.CharField(choices=[('ALL', 'Todos'), ('TEACHERS', 'Professores'), ('STUDENTS', 'Alunos'), ('GUARDIANS', 'Responsáveis'), ('CLASS', 'Turma específica')], default='ALL', max_length=20, verbose_name='Público-alvo')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público para responsáveis/alunos')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo de cancelamento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('date', models.DateField(verbose_name='Data')),
                ('type', models.CharField(choices=[('NATIONAL', 'Nacional'), ('STATE', 'Estadual'), ('MUNICIPAL', 'Municipal'), ('SCHOOL', 'Escolar')], default='NATIONAL', max_length=20, verbose_name='Tipo')),
                ('is_recurring', models.BooleanField(default=False, help_text='Quando ativo, o feriado é considerado em qualquer ano.', verbose_name='Repete todo ano')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['date'],
            },
        ),
    ]
