# Generated by Django 5.1.15 on 2026-06-30 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('widget_type', models.CharField(choices=[('KPI', 'Indicador (card)'), ('CHART', 'Grafico'), ('TABLE', 'Tabela'), ('LIST', 'Lista')], default='KPI', max_length=20, verbose_name='Tipo')),
                ('datasource', models.CharField(help_text='Metodo do DashboardSelector que alimenta o widget.', max_length=100, verbose_name='Fonte de dados')),
                ('refresh_interval', models.PositiveIntegerField(default=60, verbose_name='Intervalo de atualizacao (s)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posicao no grid')),
                ('size', models.CharField(default='medium', help_text='small, medium, large, full', max_length=10, verbose_name='Tamanho')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visivel')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuracao extra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['position'],
            },
        ),
    ]
