# Generated by Django 5.2.16 on 2026-07-11 01:08

import base.upload_validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import tenancy.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Escola')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Razao Social')),
                ('trade_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome Fantasia')),
                ('state_registration', models.CharField(blank=True, default='', max_length=20, verbose_name='Inscricao Estadual')),
                ('municipal_registration', models.CharField(blank=True, default='', max_length=20, verbose_name='Inscricao Municipal')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do Responsavel')),
                ('contact_role', models.CharField(blank=True, default='', max_length=150, verbose_name='Cargo do Responsavel')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone do Responsavel')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail do Responsavel')),
                ('address', models.JSONField(blank=True, default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', validators=[base.upload_validators.validate_image_upload])),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('academic_year_start', models.DateField(blank=True, null=True)),
                ('academic_year_end', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.school')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
            },
        ),
        migrations.CreateModel(
            name='SupportAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(max_length=500)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=tenancy.models.default_support_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access_grants', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access_grants', to='tenancy.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concessão de Acesso',
                'verbose_name_plural': 'Concessões de Acesso',
                'ordering': ['-created_at'],
                'permissions': [('access_tenant', 'Pode acessar tenant para suporte')],
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='tenancy_sup_tenant__984179_idx')],
            },
        ),
    ]
