# Generated by Django 5.1.15 on 2026-07-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_teacher_birth_date_teacher_cpf_teacher_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="rg_state",
            field=models.CharField(blank=True, default="", max_length=2, verbose_name="RG — UF"),
        ),
    ]
