# Generated by Django 5.1.4 on 2026-06-28 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("MAE", "Mãe"),
                            ("PAI", "Pai"),
                            ("AVO_F", "Avó"),
                            ("AVO_M", "Avô"),
                            ("TIA", "Tia"),
                            ("TIO", "Tio"),
                            ("IRMA", "Irmã"),
                            ("IRMAO", "Irmão"),
                            ("LEGAL", "Responsável Legal"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=10,
                        verbose_name="Parentesco",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, default="", max_length=14, verbose_name="CPF"),
                ),
                ("rg", models.CharField(blank=True, default="", max_length=20, verbose_name="RG")),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "phone_whatsapp",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsável",
                "verbose_name_plural": "Responsáveis",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Responsável Principal"),
                ),
                (
                    "has_custody",
                    models.BooleanField(default=True, verbose_name="Possui Guarda Legal"),
                ),
                (
                    "can_pickup",
                    models.BooleanField(default=True, verbose_name="Autorizado a Buscar"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="guardians.guardian",
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to="students.student",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo Aluno-Responsável",
                "verbose_name_plural": "Vínculos Aluno-Responsável",
                "ordering": ["-is_primary", "guardian__user__first_name"],
                "unique_together": {("student", "guardian")},
            },
        ),
    ]
