# Generated by Django 5.2.16 on 2026-07-13 22:38

import base.media
import base.upload_validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('avatar', models.ImageField(blank=True, null=True, storage=base.media.get_private_storage, upload_to=base.media.TenantMediaPath('avatars/guardians'), validators=[base.upload_validators.validate_image_upload])),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não Binário'), ('NI', 'Prefiro não informar')], default='NI', max_length=2, verbose_name='Gênero')),
                ('nationality', models.CharField(blank=True, default='Brasileiro(a)', max_length=100, verbose_name='Nacionalidade')),
                ('cpf', models.CharField(blank=True, default='', max_length=14, verbose_name='CPF')),
                ('rg_number', models.CharField(blank=True, default='', max_length=20, verbose_name='RG — Número')),
                ('rg_issuer', models.CharField(blank=True, default='', max_length=50, verbose_name='RG — Órgão Emissor')),
                ('rg_state', models.CharField(blank=True, default='', max_length=2, verbose_name='RG — UF')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('phone_whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('phone_mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='Celular')),
                ('accepts_email_notifications', models.BooleanField(default=False, verbose_name='Aceita notificações por e-mail')),
                ('accepts_whatsapp_notifications', models.BooleanField(default=False, verbose_name='Aceita notificações por WhatsApp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('relationship_type', models.CharField(choices=[('MAE', 'Mãe'), ('PAI', 'Pai'), ('AVO_F', 'Avó'), ('AVO_M', 'Avô'), ('TIA', 'Tia'), ('TIO', 'Tio'), ('IRMA', 'Irmã'), ('IRMAO', 'Irmão'), ('LEGAL', 'Responsável Legal'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='Parentesco')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Responsável Principal')),
                ('has_custody', models.BooleanField(default=True, verbose_name='Possui Guarda Legal')),
                ('can_pickup', models.BooleanField(default=True, verbose_name='Autorizado a Buscar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='guardians.guardian', verbose_name='Responsável')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student', verbose_name='Aluno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo Aluno-Responsável',
                'verbose_name_plural': 'Vínculos Aluno-Responsável',
                'ordering': ['-is_primary', 'guardian__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['cpf'], name='guardians_g_cpf_7f662f_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['email'], name='guardians_g_email_8e3dad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentguardian',
            unique_together={('student', 'guardian')},
        ),
    ]
