# Generated by Django 5.1.15 on 2026-07-01 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='rg',
        ),
        migrations.AddField(
            model_name='guardian',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não Binário'), ('NI', 'Prefiro não informar')], default='NI', max_length=2, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='nationality',
            field=models.CharField(blank=True, default='Brasileiro(a)', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='phone_mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='rg_issuer',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='RG — Órgão Emissor'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='rg_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RG — Número'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='rg_state',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhao'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PR', 'Parana'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'Sao Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='', max_length=2, verbose_name='RG — UF'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['cpf'], name='guardians_g_cpf_7f662f_idx'),
        ),
    ]
