# Generated by Django 5.2.16 on 2026-07-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='accepts_email_notifications',
            field=models.BooleanField(default=False, verbose_name='Aceita notificações por e-mail'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='accepts_whatsapp_notifications',
            field=models.BooleanField(default=False, verbose_name='Aceita notificações por WhatsApp'),
        ),
    ]
