# Generated by Django 5.1.15 on 2026-07-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardians", "0002_remove_guardian_rg_guardian_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardian",
            name="rg_state",
            field=models.CharField(blank=True, default="", max_length=2, verbose_name="RG — UF"),
        ),
    ]
