# Generated by Django 5.2.16 on 2026-07-19 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0002_initial"),
        ("guardians", "0001_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyDiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("date", models.DateField(verbose_name="Data")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observações")),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_diaries",
                        to="classes.class",
                        verbose_name="Turma",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_diaries",
                        to="students.student",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_diaries",
                        to="teachers.teacher",
                        verbose_name="Professor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agenda Diária",
                "verbose_name_plural": "Agendas Diárias",
                "ordering": ["-date", "student__first_name"],
            },
        ),
        migrations.CreateModel(
            name="DiaryCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "section",
                    models.CharField(
                        choices=[("ROUTINE", "Como foi o dia"), ("MEAL", "Alimentação")],
                        default="ROUTINE",
                        max_length=12,
                        verbose_name="Seção",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Resposta obrigatória"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Ativo na Agenda")),
                ("applies_morning", models.BooleanField(default=True, verbose_name="Manhã")),
                ("applies_afternoon", models.BooleanField(default=True, verbose_name="Tarde")),
                ("applies_full", models.BooleanField(default=True, verbose_name="Integral")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria da Agenda",
                "verbose_name_plural": "Categorias da Agenda",
                "ordering": ["section", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DiaryOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(max_length=100, verbose_name="Opção")),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Disponível na Agenda"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="student_diary.diarycategory",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opção da Agenda",
                "verbose_name_plural": "Opções da Agenda",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="DiaryAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="student_diary.dailydiary",
                        verbose_name="Agenda",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="student_diary.diarycategory",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="student_diary.diaryoption",
                        verbose_name="Opção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta da Agenda",
                "verbose_name_plural": "Respostas da Agenda",
                "ordering": ["category__section", "category__display_order", "category__name"],
            },
        ),
        migrations.CreateModel(
            name="DiaryPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("revision_number", models.PositiveSmallIntegerField(verbose_name="Revisão")),
                ("published_at", models.DateTimeField(verbose_name="Publicado em")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_diary_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publicação da Agenda",
                "verbose_name_plural": "Publicações da Agenda",
                "ordering": ["-revision_number"],
            },
        ),
        migrations.CreateModel(
            name="DiaryPublishedEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "answers_snapshot",
                    models.JSONField(default=list, verbose_name="Respostas publicadas"),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="student_diary.diarypublication",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_diary_entries",
                        to="students.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agenda Publicada do Aluno",
                "verbose_name_plural": "Agendas Publicadas dos Alunos",
                "ordering": ["-publication__published_at"],
            },
        ),
        migrations.CreateModel(
            name="DiarySheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PENDING_REVIEW", "Em revisão"),
                            ("CHANGES_REQUESTED", "Devolvido para correção"),
                            ("PUBLISHED", "Publicado"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "review_feedback",
                    models.TextField(blank=True, default="", verbose_name="Motivo da devolução"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Enviado em"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Revisado em"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diary_sheets",
                        to="classes.class",
                        verbose_name="Turma",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_diary_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_diary_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Folha da Agenda",
                "verbose_name_plural": "Folhas da Agenda",
                "ordering": ["-date", "class_obj__name"],
            },
        ),
        migrations.AddField(
            model_name="diarypublication",
            name="sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publications",
                to="student_diary.diarysheet",
            ),
        ),
        migrations.CreateModel(
            name="DiaryViewReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "notification_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Notificação interna"),
                ),
                (
                    "first_viewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Primeira abertura"),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Última abertura"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Visualizações"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="view_receipts",
                        to="student_diary.diarypublishedentry",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diary_view_receipts",
                        to="guardians.guardian",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visualização da Agenda",
                "verbose_name_plural": "Visualizações da Agenda",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dailydiary",
            index=models.Index(fields=["class_obj", "date"], name="student_dia_class_o_9f9f7e_idx"),
        ),
        migrations.AddIndex(
            model_name="dailydiary",
            index=models.Index(fields=["student", "date"], name="student_dia_student_d51470_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailydiary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                fields=("student", "class_obj", "date"),
                name="unique_active_student_daily_diary",
            ),
        ),
        migrations.AddIndex(
            model_name="diarycategory",
            index=models.Index(
                fields=["section", "display_order", "is_active"],
                name="student_dia_section_c55ba8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="diarycategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                fields=("name",),
                name="unique_active_diary_category_name",
            ),
        ),
        migrations.AddIndex(
            model_name="diaryoption",
            index=models.Index(
                fields=["category", "display_order"], name="student_dia_categor_f7cf63_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diaryoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                fields=("category", "label"),
                name="unique_active_diary_category_option",
            ),
        ),
        migrations.AddIndex(
            model_name="diaryanswer",
            index=models.Index(fields=["diary", "category"], name="student_dia_diary_i_d0a038_idx"),
        ),
        migrations.AddConstraint(
            model_name="diaryanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                fields=("diary", "category"),
                name="unique_active_diary_category_answer",
            ),
        ),
        migrations.AddIndex(
            model_name="diarypublishedentry",
            index=models.Index(
                fields=["student", "publication"], name="student_dia_student_5f4120_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diarypublishedentry",
            constraint=models.UniqueConstraint(
                fields=("publication", "student"), name="unique_diary_publication_student"
            ),
        ),
        migrations.AddIndex(
            model_name="diarysheet",
            index=models.Index(fields=["status", "date"], name="student_dia_status_5ab5bc_idx"),
        ),
        migrations.AddIndex(
            model_name="diarysheet",
            index=models.Index(fields=["class_obj"], name="student_dia_class_o_2ccb74_idx"),
        ),
        migrations.AddConstraint(
            model_name="diarysheet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                fields=("class_obj", "date"),
                name="unique_active_diary_sheet",
            ),
        ),
        migrations.AddIndex(
            model_name="diarypublication",
            index=models.Index(
                fields=["sheet", "-revision_number"], name="student_dia_sheet_i_490744_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diarypublication",
            constraint=models.UniqueConstraint(
                fields=("sheet", "revision_number"), name="unique_diary_publication_revision"
            ),
        ),
        migrations.AddIndex(
            model_name="diaryviewreceipt",
            index=models.Index(
                fields=["guardian", "first_viewed_at"], name="student_dia_guardia_fa0f5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diaryviewreceipt",
            index=models.Index(fields=["entry"], name="student_dia_entry_i_21e4c0_idx"),
        ),
        migrations.AddConstraint(
            model_name="diaryviewreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                fields=("entry", "guardian"),
                name="unique_active_diary_entry_guardian",
            ),
        ),
    ]
