# Generated by Django 5.2.16 on 2026-07-13 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(verbose_name='Data')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_diaries', to='classes.class', verbose_name='Turma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_diaries', to='students.student', verbose_name='Aluno')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_diaries', to='teachers.teacher', verbose_name='Professor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agenda Diária',
                'verbose_name_plural': 'Agendas Diárias',
                'ordering': ['-date', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DiaryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('code', models.CharField(choices=[('MOOD', 'Humor'), ('REST', 'Descanso'), ('BOWEL_MOVEMENT', 'Evacuação'), ('PARTICIPATION', 'Participação')], max_length=20, unique=True, verbose_name='Aspecto estruturado')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obrigatória')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Ativo na rotina')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria da Agenda',
                'verbose_name_plural': 'Categorias da Agenda',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiaryMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('meal_type', models.CharField(choices=[('MORNING_SNACK', 'Café da manhã'), ('LUNCH', 'Almoço'), ('AFTERNOON_SNACK', 'Café da tarde')], max_length=20, verbose_name='Refeição')),
                ('status', models.CharField(choices=[('ATE_WELL', 'Comeu bem'), ('ATE_PARTIALLY', 'Comeu parcialmente'), ('DID_NOT_EAT', 'Não comeu'), ('NOT_PRESENT', 'Não estava presente')], max_length=20, verbose_name='Situação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='student_diary.dailydiary', verbose_name='Agenda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alimentação da Agenda',
                'verbose_name_plural': 'Alimentações da Agenda',
                'ordering': ['meal_type'],
            },
        ),
        migrations.CreateModel(
            name='DiaryOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=100, verbose_name='Opção')),
                ('code', models.CharField(choices=[('MOOD_HAPPY', 'Alegre'), ('MOOD_CALM', 'Tranquilo'), ('MOOD_AGITATED', 'Agitado'), ('MOOD_IRRITATED', 'Irritado'), ('MOOD_TEARFUL', 'Choroso'), ('MOOD_SLEEPY', 'Sonolento'), ('REST_SLEPT_WELL', 'Dormiu bem'), ('REST_RESTLESS', 'Sono agitado'), ('REST_ONLY_RESTED', 'Apenas descansou'), ('REST_NO_SLEEP', 'Não dormiu'), ('BOWEL_NONE', 'Não evacuou'), ('BOWEL_NORMAL', 'Normal'), ('BOWEL_SOFT', 'Pastosa'), ('BOWEL_LIQUID', 'Líquida'), ('PARTICIPATED_WELL', 'Participou bem'), ('PARTICIPATED_PART', 'Participou parcialmente'), ('DID_NOT_PARTICIPATE', 'Não quis participar')], max_length=24, verbose_name='Opção estruturada')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='student_diary.diarycategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opção da Agenda',
                'verbose_name_plural': 'Opções da Agenda',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DiaryAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='student_diary.dailydiary', verbose_name='Agenda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='student_diary.diarycategory', verbose_name='Categoria')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='student_diary.diaryoption', verbose_name='Opção')),
            ],
            options={
                'verbose_name': 'Resposta da Agenda',
                'verbose_name_plural': 'Respostas da Agenda',
                'ordering': ['category__display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='dailydiary',
            index=models.Index(fields=['class_obj', 'date'], name='student_dia_class_o_9f9f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydiary',
            index=models.Index(fields=['student', 'date'], name='student_dia_student_d51470_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailydiary',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('student', 'class_obj', 'date'), name='unique_active_student_daily_diary'),
        ),
        migrations.AddIndex(
            model_name='diarycategory',
            index=models.Index(fields=['display_order', 'is_active'], name='student_dia_display_697ed0_idx'),
        ),
        migrations.AddConstraint(
            model_name='diarycategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('name',), name='unique_active_diary_category_name'),
        ),
        migrations.AddIndex(
            model_name='diarymeal',
            index=models.Index(fields=['diary', 'meal_type'], name='student_dia_diary_i_945444_idx'),
        ),
        migrations.AddConstraint(
            model_name='diarymeal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('diary', 'meal_type'), name='unique_active_diary_meal'),
        ),
        migrations.AddIndex(
            model_name='diaryoption',
            index=models.Index(fields=['category', 'display_order'], name='student_dia_categor_f7cf63_idx'),
        ),
        migrations.AddConstraint(
            model_name='diaryoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('category', 'label'), name='unique_active_diary_category_option'),
        ),
        migrations.AddConstraint(
            model_name='diaryoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('category', 'code'), name='unique_active_diary_option_code'),
        ),
        migrations.AddIndex(
            model_name='diaryanswer',
            index=models.Index(fields=['diary', 'category'], name='student_dia_diary_i_d0a038_idx'),
        ),
        migrations.AddConstraint(
            model_name='diaryanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('diary', 'category'), name='unique_active_diary_category_answer'),
        ),
    ]
