# Generated by Django 5.2.16 on 2026-07-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ASPECTS = (
    (
        "MOOD",
        "Humor",
        1,
        (
            ("MOOD_HAPPY", "Alegre"),
            ("MOOD_CALM", "Tranquilo"),
            ("MOOD_AGITATED", "Agitado"),
            ("MOOD_IRRITATED", "Irritado"),
            ("MOOD_TEARFUL", "Choroso"),
            ("MOOD_SLEEPY", "Sonolento"),
        ),
    ),
    (
        "REST",
        "Descanso",
        2,
        (
            ("REST_SLEPT_WELL", "Dormiu bem"),
            ("REST_RESTLESS", "Sono agitado"),
            ("REST_ONLY_RESTED", "Apenas descansou"),
            ("REST_NO_SLEEP", "Não dormiu"),
        ),
    ),
    (
        "BOWEL_MOVEMENT",
        "Evacuação",
        3,
        (
            ("BOWEL_NONE", "Não evacuou"),
            ("BOWEL_NORMAL", "Normal"),
            ("BOWEL_SOFT", "Pastosa"),
            ("BOWEL_LIQUID", "Líquida"),
        ),
    ),
    (
        "PARTICIPATION",
        "Participação",
        4,
        (
            ("PARTICIPATED_WELL", "Participou bem"),
            ("PARTICIPATED_PART", "Participou parcialmente"),
            ("DID_NOT_PARTICIPATE", "Não quis participar"),
        ),
    ),
)


def create_fixed_routine_aspects(apps, schema_editor):
    """Cria o catálogo fixo e mantém categorias anteriores como legado."""
    DiaryCategory = apps.get_model("student_diary", "DiaryCategory")
    DiaryOption = apps.get_model("student_diary", "DiaryOption")
    for code, name, order, options in ASPECTS:
        conflict = DiaryCategory._base_manager.filter(name=name, code__isnull=True).first()
        if conflict:
            DiaryCategory._base_manager.filter(pk=conflict.pk).update(
                name=f"{name} (legado {str(conflict.pk)[:8]})"
            )
        category = DiaryCategory._base_manager.create(
            code=code,
            name=name,
            display_order=order,
            is_required=True,
            is_enabled=True,
        )
        for option_order, (option_code, label) in enumerate(options, start=1):
            DiaryOption._base_manager.create(
                category=category,
                code=option_code,
                label=label,
                display_order=option_order,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("student_diary", "0001_initial"),
        ("teachers", "0002_teacher_accepts_email_notifications_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diarycategory",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MOOD", "Humor"),
                    ("REST", "Descanso"),
                    ("BOWEL_MOVEMENT", "Evacuação"),
                    ("PARTICIPATION", "Participação"),
                ],
                max_length=20,
                null=True,
                verbose_name="Aspecto estruturado",
            ),
        ),
        migrations.AddField(
            model_name="diarycategory",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="Ativo na rotina"),
        ),
        migrations.AddField(
            model_name="diaryoption",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MOOD_HAPPY", "Alegre"),
                    ("MOOD_CALM", "Tranquilo"),
                    ("MOOD_AGITATED", "Agitado"),
                    ("MOOD_IRRITATED", "Irritado"),
                    ("MOOD_TEARFUL", "Choroso"),
                    ("MOOD_SLEEPY", "Sonolento"),
                    ("REST_SLEPT_WELL", "Dormiu bem"),
                    ("REST_RESTLESS", "Sono agitado"),
                    ("REST_ONLY_RESTED", "Apenas descansou"),
                    ("REST_NO_SLEEP", "Não dormiu"),
                    ("BOWEL_NONE", "Não evacuou"),
                    ("BOWEL_NORMAL", "Normal"),
                    ("BOWEL_SOFT", "Pastosa"),
                    ("BOWEL_LIQUID", "Líquida"),
                    ("PARTICIPATED_WELL", "Participou bem"),
                    ("PARTICIPATED_PART", "Participou parcialmente"),
                    ("DID_NOT_PARTICIPATE", "Não quis participar"),
                ],
                max_length=24,
                null=True,
                verbose_name="Opção estruturada",
            ),
        ),
        migrations.AlterField(
            model_name="dailydiary",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_diaries",
                to="teachers.teacher",
                verbose_name="Professor",
            ),
        ),
        migrations.AlterField(
            model_name="diarymeal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("MORNING_SNACK", "Café da manhã"),
                    ("LUNCH", "Almoço"),
                    ("AFTERNOON_SNACK", "Café da tarde"),
                ],
                max_length=20,
                verbose_name="Refeição",
            ),
        ),
        migrations.AlterField(
            model_name="diarymeal",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATE_WELL", "Comeu bem"),
                    ("ATE_PARTIALLY", "Comeu parcialmente"),
                    ("DID_NOT_EAT", "Não comeu"),
                    ("NOT_PRESENT", "Não estava presente"),
                ],
                max_length=20,
                verbose_name="Situação",
            ),
        ),
        migrations.RunPython(create_fixed_routine_aspects, migrations.RunPython.noop),
    ]
