# Generated by Django 5.2.16 on 2026-07-16 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def publish_historical_diaries(apps, schema_editor):
    """Preserva agendas existentes como revisão publicada número 1."""
    DailyDiary = apps.get_model("student_diary", "DailyDiary")
    DiaryAnswer = apps.get_model("student_diary", "DiaryAnswer")
    DiaryMeal = apps.get_model("student_diary", "DiaryMeal")
    DiarySheet = apps.get_model("student_diary", "DiarySheet")
    DiaryPublication = apps.get_model("student_diary", "DiaryPublication")
    DiaryPublishedEntry = apps.get_model("student_diary", "DiaryPublishedEntry")
    meal_labels = {
        "MORNING_SNACK": "Café da manhã",
        "LUNCH": "Almoço",
        "AFTERNOON_SNACK": "Café da tarde",
    }
    status_labels = {
        "ATE_WELL": "Comeu bem",
        "ATE_PARTIALLY": "Comeu parcialmente",
        "DID_NOT_EAT": "Não comeu",
        "NOT_PRESENT": "Não estava presente",
    }
    groups = DailyDiary.objects.filter(
        is_active=True, deleted_at__isnull=True
    ).values_list("class_obj_id", "date").distinct()
    for class_id, diary_date in groups.iterator():
        diaries = list(
            DailyDiary.objects.filter(
                class_obj_id=class_id,
                date=diary_date,
                is_active=True,
                deleted_at__isnull=True,
            ).order_by("created_at")
        )
        first = diaries[0]
        actor_id = first.updated_by_id or first.created_by_id
        published_at = max(diary.updated_at for diary in diaries)
        sheet = DiarySheet.objects.create(
            class_obj_id=class_id,
            date=diary_date,
            status="PUBLISHED",
            reviewed_at=published_at,
            reviewed_by_id=actor_id,
            created_by_id=first.created_by_id,
            updated_by_id=actor_id,
        )
        publication = DiaryPublication.objects.create(
            sheet=sheet,
            revision_number=1,
            published_at=published_at,
            published_by_id=actor_id,
            created_by_id=first.created_by_id,
            updated_by_id=actor_id,
        )
        for diary in diaries:
            routine = [
                {
                    "category": answer.category.name,
                    "category_code": answer.category.code,
                    "option": answer.option.label,
                    "option_code": answer.option.code,
                }
                for answer in DiaryAnswer.objects.filter(
                    diary_id=diary.id, is_active=True, deleted_at__isnull=True
                ).select_related("category", "option")
            ]
            meals = [
                {
                    "meal_type": meal.meal_type,
                    "meal_label": meal_labels.get(meal.meal_type, meal.meal_type),
                    "status": meal.status,
                    "status_label": status_labels.get(meal.status, meal.status),
                }
                for meal in DiaryMeal.objects.filter(
                    diary_id=diary.id, is_active=True, deleted_at__isnull=True
                )
            ]
            DiaryPublishedEntry.objects.create(
                publication=publication,
                student_id=diary.student_id,
                routine_snapshot=routine,
                meals_snapshot=meals,
                notes=diary.notes,
                created_by_id=diary.created_by_id,
                updated_by_id=diary.updated_by_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('guardians', '0001_initial'),
        ('student_diary', '0002_seed_fixed_aspects'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('revision_number', models.PositiveSmallIntegerField(verbose_name='Revisão')),
                ('published_at', models.DateTimeField(verbose_name='Publicado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_diary_revisions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicação da Agenda',
                'verbose_name_plural': 'Publicações da Agenda',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='DiaryPublishedEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('routine_snapshot', models.JSONField(default=list, verbose_name='Rotina publicada')),
                ('meals_snapshot', models.JSONField(default=list, verbose_name='Alimentação publicada')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='student_diary.diarypublication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_diary_entries', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agenda Publicada do Aluno',
                'verbose_name_plural': 'Agendas Publicadas dos Alunos',
                'ordering': ['-publication__published_at'],
            },
        ),
        migrations.CreateModel(
            name='DiarySheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING_REVIEW', 'Em revisão'), ('CHANGES_REQUESTED', 'Devolvido para correção'), ('PUBLISHED', 'Publicado')], default='DRAFT', max_length=24)),
                ('review_feedback', models.TextField(blank=True, default='', verbose_name='Motivo da devolução')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_sheets', to='classes.class', verbose_name='Turma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_diary_sheets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_diary_sheets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folha da Agenda',
                'verbose_name_plural': 'Folhas da Agenda',
                'ordering': ['-date', 'class_obj__name'],
            },
        ),
        migrations.AddField(
            model_name='diarypublication',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='student_diary.diarysheet'),
        ),
        migrations.CreateModel(
            name='DiaryViewReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('notification_id', models.UUIDField(blank=True, null=True, verbose_name='Notificação interna')),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Primeira abertura')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Última abertura')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='view_receipts', to='student_diary.diarypublishedentry')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_view_receipts', to='guardians.guardian')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização da Agenda',
                'verbose_name_plural': 'Visualizações da Agenda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='diarypublishedentry',
            index=models.Index(fields=['student', 'publication'], name='student_dia_student_5f4120_idx'),
        ),
        migrations.AddConstraint(
            model_name='diarypublishedentry',
            constraint=models.UniqueConstraint(fields=('publication', 'student'), name='unique_diary_publication_student'),
        ),
        migrations.AddIndex(
            model_name='diarysheet',
            index=models.Index(fields=['status', 'date'], name='student_dia_status_5ab5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='diarysheet',
            index=models.Index(fields=['class_obj'], name='student_dia_class_o_2ccb74_idx'),
        ),
        migrations.AddConstraint(
            model_name='diarysheet',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('class_obj', 'date'), name='unique_active_diary_sheet'),
        ),
        migrations.AddIndex(
            model_name='diarypublication',
            index=models.Index(fields=['sheet', '-revision_number'], name='student_dia_sheet_i_490744_idx'),
        ),
        migrations.AddConstraint(
            model_name='diarypublication',
            constraint=models.UniqueConstraint(fields=('sheet', 'revision_number'), name='unique_diary_publication_revision'),
        ),
        migrations.AddIndex(
            model_name='diaryviewreceipt',
            index=models.Index(fields=['guardian', 'first_viewed_at'], name='student_dia_guardia_fa0f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryviewreceipt',
            index=models.Index(fields=['entry'], name='student_dia_entry_i_21e4c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='diaryviewreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('entry', 'guardian'), name='unique_active_diary_entry_guardian'),
        ),
        migrations.RunPython(publish_historical_diaries, migrations.RunPython.noop),
    ]
