# Generated by Django 5.2.16 on 2026-07-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('operation', models.CharField(choices=[('INSERT', 'Inserção'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('RESTORE', 'Restauração')], db_index=True, max_length=10)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('platform_actor_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('support_grant_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
