# Generated by Django 5.1.15 on 2026-07-08 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0003_alter_student_rg_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('academic_year', models.PositiveIntegerField(verbose_name='Ano Letivo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Plano')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('CLOSED', 'Encerrado')], default='DRAFT', max_length=20, verbose_name='Situacao')),
                ('billing_frequency', models.CharField(choices=[('MONTHLY', 'Mensal'), ('BIMONTHLY', 'Bimestral'), ('QUARTERLY', 'Trimestral'), ('ANNUAL', 'Anual')], default='MONTHLY', max_length=20, verbose_name='Frequencia de Cobranca')),
                ('installment_count', models.PositiveIntegerField(verbose_name='Numero de Parcelas')),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('due_day', models.PositiveSmallIntegerField(help_text='Dia do mes para vencimento padrao das parcelas (1-28).', verbose_name='Dia de Vencimento')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Desconto por Parcela')),
                ('late_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Multa por Atraso (%)')),
                ('daily_interest_percent', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Juros Diarios (%)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_plans', to='classes.class', verbose_name='Turma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_plans', to='students.student', verbose_name='Aluno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano Financeiro',
                'verbose_name_plural': 'Planos Financeiros',
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('installment_number', models.PositiveSmallIntegerField(verbose_name='Parcela')),
                ('description', models.CharField(max_length=200, verbose_name='Descricao')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Original')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto Aplicado')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('PAID', 'Pago'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=20, verbose_name='Situacao')),
                ('cancelled_reason', models.TextField(blank=True, default='', verbose_name='Motivo de Cancelamento')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('renegotiated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renegotiated_to', to='financeiro.billingentry', verbose_name='Originada por Renegociacao')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='students.student', verbose_name='Aluno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='financeiro.financialplan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Cobranca',
                'verbose_name_plural': 'Cobrancas',
                'ordering': ['due_date', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('paid_date', models.DateField(verbose_name='Data de Pagamento')),
                ('payment_method', models.CharField(choices=[('CASH', 'Dinheiro'), ('PIX', 'PIX'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('CHECK', 'Cheque'), ('CARD', 'Cartao'), ('OTHER', 'Outro')], default='CASH', max_length=20, verbose_name='Forma de Pagamento')),
                ('reconciliation_status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Conciliado'), ('REJECTED', 'Estornado')], default='PENDING', max_length=20, verbose_name='Situacao da Conciliacao')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Conciliado em')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financeiro.billingentry', verbose_name='Cobranca')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-paid_date'],
            },
        ),
        migrations.AddIndex(
            model_name='financialplan',
            index=models.Index(fields=['status'], name='financeiro__status_cf098f_idx'),
        ),
        migrations.AddIndex(
            model_name='financialplan',
            index=models.Index(fields=['academic_year'], name='financeiro__academi_b69aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='financialplan',
            index=models.Index(fields=['class_obj', 'academic_year'], name='financeiro__class_o_95f531_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialplan',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('deleted_at__isnull', True),
                    ('is_active', True),
                    ('status__in', ['DRAFT', 'ACTIVE']),
                ),
                fields=('student', 'academic_year'),
                name='uniq_active_financial_plan_per_student_year',
            ),
        ),
        migrations.AddIndex(
            model_name='billingentry',
            index=models.Index(fields=['status'], name='financeiro__status_45906c_idx'),
        ),
        migrations.AddIndex(
            model_name='billingentry',
            index=models.Index(fields=['due_date'], name='financeiro__due_dat_7aa53e_idx'),
        ),
        migrations.AddIndex(
            model_name='billingentry',
            index=models.Index(fields=['student', 'status'], name='financeiro__student_b4d0c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billingentry',
            unique_together={('plan', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['paid_date'], name='financeiro__paid_da_db35da_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['reconciliation_status'], name='financeiro__reconci_a8ba3c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['billing', 'paid_date'], name='financeiro__billing_a4bfe9_idx'),
        ),
    ]
