# Generated by Django 5.1.15 on 2026-06-29 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('body', models.TextField(verbose_name='Mensagem')),
                ('audience', models.CharField(choices=[('ALL', 'Todos'), ('TEACHERS', 'Professores'), ('STUDENTS', 'Alunos'), ('GUARDIANS', 'Responsaveis'), ('CLASS', 'Turma especifica')], default='ALL', max_length=20, verbose_name='Publico-alvo')),
                ('send_email', models.BooleanField(default=False, verbose_name='Enviar por E-mail')),
                ('send_whatsapp', models.BooleanField(default=False, verbose_name='Enviar por WhatsApp')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.class', verbose_name='Turma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('channel', models.CharField(choices=[('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'Notificacao In-App')], max_length=20, verbose_name='Canal')),
                ('recipient_address', models.CharField(help_text='E-mail ou telefone do destinatario', max_length=200, verbose_name='Destino')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensagem de erro')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.announcement', verbose_name='Comunicado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Envio',
                'verbose_name_plural': 'Logs de Envio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'status'], name='notificatio_channel_d57783_idx'), models.Index(fields=['announcement'], name='notificatio_announc_e87bdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('channel', models.CharField(choices=[('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20, verbose_name='Canal')),
                ('type', models.CharField(choices=[('WELCOME', 'Boas-vindas'), ('ATTENDANCE_ALERT', 'Alerta de Frequencia'), ('NEW_ACTIVITY', 'Nova Atividade'), ('EVENT_REMINDER', 'Lembrete de Evento'), ('CUSTOM', 'Personalizado')], default='CUSTOM', max_length=30, verbose_name='Tipo')),
                ('subject', models.CharField(blank=True, default='', max_length=200, verbose_name='Assunto')),
                ('body', models.TextField(verbose_name='Corpo')),
                ('variables', models.JSONField(blank=True, default=dict, help_text="Ex: {'nome': 'Nome do destinatario', 'escola': 'Nome da escola'}", verbose_name='Variaveis disponiveis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagem',
                'ordering': ['name'],
                'unique_together': {('name', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('INFO', 'Informativa'), ('ALERT', 'Alerta'), ('CRITICAL', 'Critico'), ('SUCCESS', 'Sucesso')], default='INFO', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('source', models.CharField(blank=True, default='', help_text='Modulo que gerou a notificacao (attendance, activities, calendar, etc.)', max_length=50, verbose_name='Origem')),
                ('action_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Link de acao')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID de correlacao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacao',
                'verbose_name_plural': 'Notificacoes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx')],
            },
        ),
    ]
