# Generated by Django 5.2.16 on 2026-07-16 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('student_diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(max_length=30, verbose_name='Provedor')),
                ('external_event_id', models.CharField(max_length=100, unique=True, verbose_name='ID externo do evento')),
                ('event_type', models.CharField(max_length=40, verbose_name='Tipo do evento')),
                ('provider_message_id', models.CharField(max_length=100, verbose_name='ID da mensagem')),
                ('occurred_at', models.DateTimeField(verbose_name='Ocorrido em')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='messagelog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregue em'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='diary_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='student_diary.diarypublication', verbose_name='Publicação da Agenda'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Evento ocorrido em'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='last_event',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Último evento'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Provedor'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID da mensagem no provedor'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('DELIVERED', 'Entregue'), ('DELAYED', 'Entrega atrasada'), ('BOUNCED', 'Devolvido'), ('SUPPRESSED', 'Suprimido'), ('COMPLAINED', 'Marcado como spam'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['diary_publication', 'channel', 'status'], name='notificatio_diary_p_ba3b84_idx'),
        ),
        migrations.AddField(
            model_name='webhookeventreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookeventreceipt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookeventreceipt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='webhookeventreceipt',
            index=models.Index(fields=['provider', 'provider_message_id'], name='notificatio_provide_d96717_idx'),
        ),
    ]
