# Generated by Django 5.2.16 on 2026-07-13 22:38

import base.media
import base.upload_validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('JUSTIFIED', 'Justificado')], default='PRESENT', max_length=20, verbose_name='Situação')),
                ('justification', models.CharField(blank=True, default='', max_length=200, verbose_name='Justificativa')),
                ('note', models.CharField(blank=True, default='', max_length=250, verbose_name='Observação/recado')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['record__date', 'record__lesson_number', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceJustification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Término')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo')),
                ('document', models.FileField(blank=True, null=True, storage=base.media.get_private_storage, upload_to=base.media.TenantMediaPath('documents/attendance'), validators=[base.upload_validators.validate_document_upload], verbose_name='Documento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20, verbose_name='Situação')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo da rejeição')),
            ],
            options={
                'verbose_name': 'Justificativa de Ausência',
                'verbose_name_plural': 'Justificativas de Ausência',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(verbose_name='Data')),
                ('lesson_number', models.PositiveSmallIntegerField(default=1, help_text='Número da aula no dia.', verbose_name='Aula nº')),
                ('lesson_content', models.TextField(verbose_name='Conteúdo Ministrado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Registro de Chamada',
                'verbose_name_plural': 'Registros de Chamada',
                'ordering': ['-date', '-lesson_number'],
            },
        ),
    ]
