# Generated by Django 5.2.16 on 2026-07-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='note',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Observação/recado'),
        ),
    ]
